image: microsoft/dotnet:latest

stages:
    - build

variables:
    test: "Example.Test"

before_script:
    - "cd src"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"